//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MpvNet.Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MpvNet.Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///[setting]
        ///name = hwdec
        ///file = mpv
        ///default = no
        ///filter = Video
        ///url = https://mpv.io/manual/master/#options-hwdec
        ///help = Specify the hardware video decoding API that should be used if possible. Whether hardware decoding is actually done depends on the video codec. If hardware decoding is not possible, mpv will fall back on software decoding.\n\nFor more information visit:
        ///
        ///option = no            always use software decoding
        ///option = auto          enable best hw decoder
        ///option = yes           exact [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string editor_conf {
            get {
                return ResourceManager.GetString("editor_conf", resourceCulture);
            }
        }
             
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///[dark]
        ///
        ///heading     = #3C8CC8
        ///foreground  = #DDDDDD
        ///foreground2 = #AAAAAA
        ///background  = #323232
        ///highlight   = #404040
        ///
        ///menu-foreground = #DDDDDD
        ///menu-background = #323232
        ///menu-highlight  = #505050
        ///
        ///
        ///[light]
        ///
        ///heading     = #0068B2
        ///foreground  = #000000
        ///foreground2 = #4C4C4C
        ///background  = #F7F7F7
        ///highlight   = #DFDFDF
        ///
        ///menu-foreground = #000000
        ///menu-background = #DFDFDF
        ///menu-highlight  = #BFBFBF
        ///.
        /// </summary>
        internal static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
    }
}
