//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mpvnet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mpvnet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  # mpv.net key bindings, mouse bindings and context menu configuration
        /// 
        /// o           script-message mpv.net open-files #menu: O  ; Open Files...
        /// _           ignore                 #menu: _             ; -
        /// Space       cycle pause            #menu: Space, Enter  ; Play/Pause
        /// Enter       cycle pause
        /// s           stop                   #menu: S             ; Stop
        /// _           ignore                 #menu: _             ; -
        /// f           cycle fullscreen       #menu: F             ; Toggle Fullscreen
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input_conf {
            get {
                return ResourceManager.GetString("input_conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input-ar-delay = 500
        ///input-ar-rate = 20
        ///volume = 50
        ///hwdec = yes
        ///vo = direct3d
        ///keep-open = yes
        ///keep-open-pause = no
        ///osd-playing-msg = &apos;${filename}&apos;
        ///screenshot-directory = ~~desktop/.
        /// </summary>
        internal static string mpv_conf {
            get {
                return ResourceManager.GetString("mpv_conf", resourceCulture);
            }
        }
    }
}
